#!/bin/bash
set -e

N="$1"
SAVE="$2"
if SAVE=1; then
    mkdir -p experiments/tmp
fi

HIGH_ENERGY=1
SEED=0

# Latent space dim:
LSD=$(( 2 * N ))

RESULTSDIR="experiments/evaluation_error_simple"
OUTDIR="experiments/pendulum-simple/${N}"
MODEL="simple[a=$LSD,b=116]"

mkdir -p "$RESULTSDIR"
mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

./.colorize ./pendulum_error.py             \
    pendulum[n=$N,test]                     \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_*.pth"              \
    1000                                    \
    "$SAVE"                                 \
    "$HIGH_ENERGY"                          \
    "$SEED"    | tee -a "$OUTDIR/eval.txt"
