#!/bin/bash
# Usage ./train_many.sh <num_links> <num_runs>

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <num_links> <num_runs>"
    exit 1
fi

N_LINKS="$1"
N_RUNS="$2"
EXP_ID="stable"
DIRECTORY="experiments/error_${EXP_ID}"
INNER="PSD-REHU"

mkdir -p "$DIRECTORY"
# Clear tmp directory
rm -rf experiments/tmp

N_JOBS=2

for ALPHA in 0.001 #0.0001
do
    for INNER_EPSILON in 0.01 #0.005 0.001
    do
        for SMOOTH_V in 0
        do
            for REHU in 0.005 #0.001 0.0005
            do

                mkdir experiments/tmp

                NUM_RAN=0
                while [ $NUM_RAN -lt $N_RUNS ]
                do

                    # Run N_JOBS jobs in parallel
                    for n in $(seq 1 $N_JOBS) 
                    do
                        ./evaluate_stable "$EXP_ID" "$N_LINKS" "$ALPHA" "$INNER" "$INNER_EPSILON" "$SMOOTH_V" "$REHU" "1"&
                        NUM_RAN=$((NUM_RAN+1))
                    done
                    echo waiting after $NUM_RAN
                    wait
                    echo ended waiting

                done
                echo ended running jobs in parallel for $ALPHA $INNER_EPSILON $SMOOTH_V $REHU
                wait


                python3 generatePlots.py "experiments/error_${EXP_ID}/${N_LINKS}/${ALPHA}_${INNER}_${INNER_EPSILON}_${SMOOTH_V}_${REHU}"

            done
        wait
        done
    done
done

