#!/bin/bash
set -e

EXP_ID="$1"
N="$2"
ALPHA="$3"
INNER="$4"
INNER_EPSILON="$5"
SMOOTH_V="$6"
REHU="$7"
SAVE="$8" # 1 to save the errors+predictions in /tmp
if SAVE=1; then
    mkdir -p experiments/tmp
fi

# Latent space dim:
LSD=$(( 2 * N ))

RESULTSDIR="experiments/evaluation_error_stable"
OUTDIR="experiments/pendulum-${EXP_ID}/${N}_${ALPHA}_${INNER}_${INNER_EPSILON}_${SMOOTH_V}_${REHU}"
MODEL="stabledynamics[latent_space_dim=$LSD,a=$ALPHA,projfn=$INNER,projfn_eps=$INNER_EPSILON,smooth_v=$SMOOTH_V,hp=60,h=100,rehu=$REHU]"

mkdir -p "$RESULTSDIR"
mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

./.colorize ./pendulum_error.py             \
    pendulum[n=$N,test]                     \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_*.pth"              \
    1000                                    \
    "$SAVE" | tee -a "$OUTDIR/eval.txt"
