#!/bin/bash
set -e

N="$1"

# Latent space dim:
LSD=$(( 2 * N ))

CSV_FILE="experiments/evaluation_error_simple.csv"
OUTDIR="experiments/pendulum-simple/${N}"
MODEL="simple[a=$LSD,b=116]"

mkdir -p "$OUTDIR"
mkdir -p "experiments/evaluation_error_simple"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./.colorize ./train.py                      \
    --log-to "runs/$OUTDIR"                 \
    --batch-size 2000                       \
    --learning-rate "0.001"                 \
    --epochs 1000                           \
    --test-with "pendulum[n=$N,test]"       \
    "pendulum[n=$N]"                        \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

# Create CSV file with header if it does not exist
if ! [ -f "$CSV_FILE" ]; then
    echo "run,mean_error,last_error,model,n-links" >> $CSV_FILE
fi

{
./.colorize ./pendulum_error.py             \
    pendulum[n=$N,test]                     \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_*.pth"              \
    1000                                 && \
    printf $",pendulum-simple,${N}\n";                                   
} >> "$CSV_FILE"
