#!/bin/bash

for ITERATION in {1..2}
do
for ALPHA in 0.000 #0.001 0.0001
do
for INNER_EPSILON in 0.01 #0.005 0.001
do
for SMOOTH_V in 0
do
for REHU in 0.005 #0.001 0.0005
do
for LR in 0.01 0.001 #0.0001
do
./train_pendulum_stable stable "$1" "$ALPHA" PSD-REHU "$INNER_EPSILON" "$SMOOTH_V" "$REHU" "$LR" &
done
wait
done
done
done
done
done