#!/bin/bash
set -e

N="$1"
SAVE="$2"
HIGH_ENERGY="$3"
if SAVE=1; then
    mkdir -p experiments/tmp
fi

SEED=1906

# Latent space dim:
LSD=$(( 2 * N ))

RESULTSDIR="experiments/evaluation_error_simple"
OUTDIR="experiments/pendulum-simple/${N}"
MODEL="simple[a=$LSD,b=116]"

mkdir -p "$RESULTSDIR"
mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./.colorize ./train.py                      \
    --log-to "runs/$OUTDIR"                 \
    --batch-size 2000                       \
    --learning-rate "0.001"                 \
    --epochs 1000                           \
    --test-with "pendulum[n=$N,test]"       \
    "pendulum[n=$N]"                        \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

./.colorize ./pendulum_error.py             \
    pendulum[n=$N,test]                     \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_*.pth"              \
    1000                                    \
    "$SAVE"                                 \
    "$HIGH_ENERGY"                          \
    "$SEED"    | tee -a "$OUTDIR/eval.txt"
