#!/bin/bash
set -e

N="$1"
LR="$2"
LAYERSIZE="$3"
JOBID="$4"

# Latent space dim:
LSD=142
UUID=$(uuidgen)
NUM_EPOCHS=2

OUTDIR="experiments/water-simple-skip/skip_${N}_LR_${LR}_LAYERSIZE_${LAYERSIZE}/$UUID"
MODEL="simple[a=$LSD,b=$LAYERSIZE]"

mkdir -p "$OUTDIR"
echo $MODEL >"$OUTDIR/model"

date >>"$OUTDIR/progress.txt"
./.colorize ./train.py \
    --log-to "runs/$OUTDIR" \
    --batch-size 2000 \
    --learning-rate "$LR" \
    --epochs $NUM_EPOCHS \
    --test-with "waterplantskip[test,n=$N]" \
    --modeltype "SIMPLE_$LAYERSIZE-SKIP_N_$N" \
    --error-path "$OUTDIR/epoch_losses.pkl" \
    "waterplantskip[train,n=$N]" \
    "$MODEL" \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

./.colorize ./rollout_eval.py \
    --skip $N \
    --save-to "$OUTDIR/rollout_eval.pkl" \
    --save-image-to "$OUTDIR/rollout_plot.png" \
    --rollout-steps 2000 \
    --model "$MODEL" \
    --weights "$OUTDIR/checkpoint_*.pth" | tee -a "$OUTDIR/eval.txt"
