#!/bin/bash
set -e


N="$1"
LR="$2"
LAYERSIZE="$3"
JOBID="$4"


# Latent space dim:
LSD=142

OUTDIR="experiments/water-simple-skip/skip_${N}_LR_${LR}_LAYERSIZE_${LAYERSIZE}/$JOBID"
MODEL="simple[a=$LSD,b=$LAYERSIZE]"

mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./.colorize ./train.py                      \
    --log-to "runs/$OUTDIR"                 \
    --batch-size 2000                       \
    --learning-rate "$LR"                 \
    --epochs 60                         \
    --test-with "waterplantskip[test,n=$N]"       \
    --modeltype "SIMPLE_$LAYERSIZE-SKIP_N_$N"                 \
    "waterplantskip[train,n=$N]"                        \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"S