#!/bin/bash
set -e

SKIP="$1"
LR="$2"
LAYERSIZE="$3"

TRAIN_DATASET="./sine_data/train_sine.pkl" # Make it dynamic later on
TEST_DATASET="./sine_data/test_sine.pkl"
ROLLOUT_DATASET="./sine_data/test_sine.pkl"

# Latent space dim:
LSD=2 # TODO: this can be changed, the second output (Xt-1) is not needed... For now we can keep it
UUID=$(uuidgen)
NUM_EPOCHS=80

OUTDIR="sine/simple/experiments/skip_${SKIP}_LR_${LR}_LAYERSIZE_${LAYERSIZE}/$UUID"
MODEL="simple[a=$LSD,b=$LAYERSIZE]"

mkdir -p "$OUTDIR"
echo "$MODEL" >"$OUTDIR/model"

date >>"$OUTDIR/progress.txt"
./.colorize ./train.py \
    --log-to "runs/$OUTDIR" \
    --batch-size 64 \
    --learning-rate "$LR" \
    --epochs $NUM_EPOCHS \
    --train-with "sine[dataset=$TRAIN_DATASET,n=$SKIP]" \
    --test-with "sine[dataset=$TEST_DATASET,n=$SKIP]" \
    --modeltype "SIMPLE_$LAYERSIZE-SKIP_N_$SKIP" \
    --error-path "$OUTDIR/epoch_losses.pkl" \
    --save-every 15 \
    "$MODEL" \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

./.colorize ./rollout_eval.py \
    --skip "$SKIP" \
    --save-to "$OUTDIR/rollout_eval.pkl" \
    --save-image-to "$OUTDIR/rollout_plot.png" \
    --save-error-plot-to "$OUTDIR/rollout_error_plot.png" \
    --rollout-steps 1000 \
    --model "$MODEL" \
    --rollout-dataset "$ROLLOUT_DATASET" \
    --weights "$OUTDIR/checkpoint_*.pth" | tee -a "$OUTDIR/eval.txt"