#!/bin/bash
set -e

EXP_ID="$1"
ALPHA="$2"
INNER="$3"
INNER_EPSILON="$4"
SMOOTH_V="$5"
REHU="$6"
DT="$7"
SKIP="$8"
LR=${9}
LAYERSIZE=${10}
LSD=${11}
TRAIN_DATASET=${12}
TEST_DATASET=${13}
ROLLOUT_DATASET=${14}
UUID=$(uuidgen)

NUM_EPOCHS=40

OUTDIR="experiments/water-${EXP_ID}-skip/skip_${SKIP}_LR_${LR}_LAYERSIZE_${LAYERSIZE}/$UUID"
MODEL="stabledynamics[latent_space_dim=$LSD,a=$ALPHA,projfn=$INNER,projfn_eps=$INNER_EPSILON,smooth_v=$SMOOTH_V,hp=$LAYERSIZE,h=$LAYERSIZE,rehu=$REHU,dt=$DT]"

mkdir -p "$OUTDIR"

echo "$MODEL" >"$OUTDIR/model"

date >>"$OUTDIR/progress.txt"
./.colorize ./train.py \
    --log-to "runs/$OUTDIR" \
    --batch-size 2000 \
    --learning-rate "$LR" \
    --epochs $NUM_EPOCHS \
    --train-with "waterplantskip[dataset=$TRAIN_DATASET,n=$SKIP]" \
    --test-with "waterplantskip[dataset=$TEST_DATASET,n=$SKIP]" \
    --modeltype "STABLE_$LAYERSIZE-SKIP_N_$SKIP" \
    --error-path "$OUTDIR/epoch_losses.pkl" \
    --save-every 15 \
    "$MODEL" \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"

./.colorize ./rollout_eval.py \
    --skip "$SKIP" \
    --save-to "$OUTDIR/rollout_eval.pkl" \
    --save-image-to "$OUTDIR/rollout_plot.png" \
    --save-error-plot-to "$OUTDIR/rollout_error_plot.png" \
    --rollout-steps 2000 \
    --model "$MODEL" \
    --rollout-dataset "$ROLLOUT_DATASET" \
    --weights "$OUTDIR/checkpoint_*.pth" | tee -a "$OUTDIR/eval.txt"


    # Gotta add all stuff here, including dataset
