#!/bin/bash
# Usage ./train_many_simple.sh <num_links> <num_runs>

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <num_links> <num_runs>"
    exit 1
fi

N_LINKS="$1"
N_RUNS="$2"
EXP_ID="simple"
DIRECTORY="experiments/error_${EXP_ID}"

mkdir -p "$DIRECTORY"
# Clear tmp directory
rm -rf experiments/tmp

N_JOBS=2


mkdir experiments/tmp

NUM_RAN=0
while [ $NUM_RAN -lt $N_RUNS ]
do

    # Run N_JOBS jobs in parallel
    for n in $(seq 1 $N_JOBS) 
    do
        ./train_pendulum_simple "$N_LINKS" "1"&
        NUM_RAN=$((NUM_RAN+1))
    done

echo waiting after $NUM_RAN
wait
echo ended waiting

done
wait


python3 generatePlots.py "experiments/error_${EXP_ID}/${N_LINKS}"



