#!/bin/bash
set -e


N="$1"
LR="$2"


# Latent space dim:
LSD=142

OUTDIR="experiments/water-simple/"
MODEL="simple[a=$LSD,b=4096]"

mkdir -p "$OUTDIR"
echo $MODEL > "$OUTDIR/model"

date >> "$OUTDIR/progress.txt"
./.colorize ./train.py                      \
    --log-to "runs/$OUTDIR"                 \
    --batch-size 2000                       \
    --learning-rate "$LR"                 \
    --epochs 25                         \
    --test-with "waterplant[test,n=$N]"       \
    --modeltype "SIMPLE_N_$N"                 \
    "waterplant[train,n=$N]"                        \
    "$MODEL"                                \
    "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"
